// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG3RsHqsJTl1BWN3coTGpTpF3lQPqt8Gc',
    appId: '1:504027916496:web:e559fc29e48fcd5371d6d5',
    messagingSenderId: '504027916496',
    projectId: 'flutter-crud-3810d',
    authDomain: 'flutter-crud-3810d.firebaseapp.com',
    storageBucket: 'flutter-crud-3810d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW9u7rdoSrx8lNigbrSddI-xcN97cZ6jA',
    appId: '1:504027916496:android:bf1584af376a9a1571d6d5',
    messagingSenderId: '504027916496',
    projectId: 'flutter-crud-3810d',
    storageBucket: 'flutter-crud-3810d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy7j5l84dyAr_fwQ0GaubFLJvWxqVMLZk',
    appId: '1:504027916496:ios:13ffe4c86021194c71d6d5',
    messagingSenderId: '504027916496',
    projectId: 'flutter-crud-3810d',
    storageBucket: 'flutter-crud-3810d.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy7j5l84dyAr_fwQ0GaubFLJvWxqVMLZk',
    appId: '1:504027916496:ios:13ffe4c86021194c71d6d5',
    messagingSenderId: '504027916496',
    projectId: 'flutter-crud-3810d',
    storageBucket: 'flutter-crud-3810d.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG3RsHqsJTl1BWN3coTGpTpF3lQPqt8Gc',
    appId: '1:504027916496:web:1a3926f1432c1a9571d6d5',
    messagingSenderId: '504027916496',
    projectId: 'flutter-crud-3810d',
    authDomain: 'flutter-crud-3810d.firebaseapp.com',
    storageBucket: 'flutter-crud-3810d.appspot.com',
  );
}
